version: '3.8'
services:
  fastapi:
    build: ./fast/.
    volumes:
      - ./fast/app:/app
    ports:
      - "8000:8000"
    env_file:
      - fast/app/.env
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=1 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  default:
    external:
      name: bridge
  backend:
    name: backend
    driver: bridge
    external: true